image: Visual Studio 2017

platform:
  - x64

configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount

build_script:
  - git config --global core.autocrlf true
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ughub/ughub install ugcore CrackGenerator tetgen
  
  - cmake -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=x64 -DTARGET=ugshell -Dtetgen=ON -DLAPACK=OFF -DBLAS=OFF -DDIM="3" -DCrackGenerator=ON  -DCOMPILE_INFO=OFF -DSTATIC_BUILD=ON -DEMBEDDED_PLUGINS=ON  -G"Visual Studio 15 2017 Win64"
  - MSBuild .\ug4.sln  /property:Configuration=Release /property:Platform=x64
  - ugshell.exe -call "print(\"it works\")"
  
