platform:
  - x64

image: Visual Studio 2017

configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount

install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'

build_script:
  - git config --global core.autocrlf true
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub addsource neurobox https://github.com/NeuroBox3D/neurobox-packages.git
  - ughub/ughub install ugcore CrackGenerator
  - cmake -DCMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE=x64 -DTARGET=ugshell -DLAPACK=OFF -DBLAS=OFF -DDIM="3" -DCrackGenerator=ON  -DCOMPILE_INFO=OFF -DEMBEDDED_PLUGINS=ON  -G"Visual Studio 15 2017 Win64"
  - MSBuild .\ug4.sln  /property:Configuration=Release /property:Platform=x64
