#ifndef UG__PLUGINS__CRACK_GENERATOR__CRACK_GENERATOR_H
#define  UG__PLUGINS__CRACK_GENERATOR__CRACK_GENERATOR_H

namespace ug {
  void BuildCrack();
}

#endif /// UG__PLUGINS__CRACK_GENERATOR__CRACK_GENERATOR_H
